% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
\setcounter{section}{-1}
\usepackage{fvextra}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{
  showspaces = false,
  showtabs = false,
  breaklines,
  commandchars=\\\{\}

\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={QRM II Graded Assignment (12), Period 1 2025},
  pdfauthor={Fill in your group number and names here},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{QRM II Graded Assignment (12), Period 1 2025}
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
\subtitle{Material by Sjoerd van Alten and Klervie Toczé}
\author{Fill in your group number and names here}
\date{19-09-2025}

\begin{document}
\maketitle

\section{Introduction}\label{introduction}

This assignment is to be completed in groups of 3-4. Further, all
students in your group need to be assigned to the same R tutorial group
(Friday's tutorial). You can sign yourself up for a group on Canvas.
Please do so
\textbf{before the start of your first R tutorial on Friday September 5th.}
You can use the Discussion Board in Canvas if you do not have a group
yet or if your group is incomplete.

The assignment has 5 parts, and each part corresponds to the course
material of that week (with the exclusion of week 6, for which there is
no R programming material).

You are supposed to hand in these assignments on Canvas at the following
dates:

\begin{itemize}
\tightlist
\item
  \textbf{Deadline 1} \emph{Thursday September 25th, at 23:59pm}: you
  are supposed to hand in weeks 1, 2, and 3 of this assignment. This
  will determine 18\% of your overall course grade
\item
  \textbf{Deadline 2} \emph{Thursday October 9th, at 23:59pm}: you are
  supposed to hand in weeks 4, and 5 of this assignment. This will
  determine 12\% of your overall course grade
\end{itemize}

The R tutorials (each Friday) will consist of two halves. During the
first half, you will discuss the tutorial exercises. These can be
downloaded separately from Canvas. During the second half, you can work
on this graded assignment within your own group. The purpose is that you
find out how to work with R for doing statistical analyses by yourself.
The tutorial exercises are meant to teach you basic commands to get you
started, but to answer the problem sets in this assignment, you might
need to research your own solutions, and use functions and commands not
described in the tutorial exercises. Learning how to solve your own
research problems is integral part of learning R. When you and your
group get stuck on how to approach an exercise, the hierarchy in finding
your way is as follows:

\begin{itemize}
\tightlist
\item
  use the concepts from the tutorial exercises;
\item
  use the cheat sheets available on Canvas;
\item
  use Google, YouTube, StackOverflow, or another website;
\item
  ask the teacher.
\end{itemize}

The use of generative AI is \textbf{not} permitted and may result in a
grade of 0. See the AI protocol in the course manual for details.

To answer the assignment, you can simply fill out this R markdown
document. There are designated places which you can fill with R code.
There are also designated spaces for you to answer each question. Often,
the structure of an answer will be as follows. First, you type the R
code in the designated box. This will show how you analyzed the data to
get the answer to the question. Below the box for the R code, you will
then summarize your answer to the question, i.e.~what are the
conclusions that you draw from the data analysis?

When handing in, you are supposed to submit this .Rmd file, and a
knitted version of this document. You can knit this document to pdf,
word, or html. Knitting to pdf requires you to have a .tex distribution
installed on your computer. Knitting to Word requires you to have Word
installed.

The exercises are designed such that you should be able to finish the
majority of them during the tutorial each week. If you are not able to
finish them fully during that time, you are expected to work on it in
your own time using the computers on campus or your own device. It is
best to meet as a group in-person when working together. If you want to
work remotely, github is a good platform to guarantee smooth
collaboration. Alternatively, you can email this .Rmd file back and
forth to one another as a group, but this is not recommended as it is
more cumbersome.

We encourage you to keep your code blocks, printing statements, and
final answers, as short as possible. In any case, there is a page limit
of 6 pages per week, which encompasses the total length of this document
which consists of the questions, your coding lines, and your answers.
When your answers to questions of the respective week exceed this page
limit, they will not be graded, resulting in zero points.

Each week consists of 1, 2, or 3 subquestions. The total amount of
points you can earn per week is 20 points.

\section{Week 1}\label{week-1}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Find the dataset ``movies4.tsv'' on Canvas. Describe your data set:
  How many observations does it have. How many variables are there? How
  many subjects? What consists of a subject? \textbf{[4 points]}
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{setwd}\NormalTok{(}\StringTok{"C:/Users/basvw/OneDrive/Quantative Research Methods/R group assignment/R{-}Assignment{-}61"}\NormalTok{)}

\FunctionTok{library}\NormalTok{(readr)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: package 'readr' was built under R version 4.5.1
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(tidyverse)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: package 'tidyverse' was built under R version 4.5.1
\end{verbatim}

\begin{verbatim}
## Warning: package 'ggplot2' was built under R version 4.5.1
\end{verbatim}

\begin{verbatim}
## Warning: package 'dplyr' was built under R version 4.5.1
\end{verbatim}

\begin{verbatim}
## Warning: package 'stringr' was built under R version 4.5.1
\end{verbatim}

\begin{verbatim}
## -- Attaching core tidyverse packages ------------------------ tidyverse 2.0.0 --
## v dplyr     1.1.4     v purrr     1.0.4
## v forcats   1.0.0     v stringr   1.5.1
## v ggplot2   3.5.2     v tibble    3.2.1
## v lubridate 1.9.4     v tidyr     1.3.1
## -- Conflicts ------------------------------------------ tidyverse_conflicts() --
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()
## i Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Movies\_4 }\OtherTok{\textless{}{-}} \FunctionTok{read\_tsv}\NormalTok{(}\StringTok{"movies4.tsv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Rows: 808 Columns: 19
## -- Column specification --------------------------------------------------------
## Delimiter: "\t"
## chr   (8): keywords, original_language, title, genre, first_actor, first_act...
## dbl  (10): index, budget, popularity, revenue, runtime, vote_average, vote_c...
## date  (1): release_date
## 
## i Use `spec()` to retrieve the full column specification for this data.
## i Specify the column types or set `show_col_types = FALSE` to quiet this message.
\end{verbatim}

\textbf{Your Answer:} This data has information about movies and
includes 808 observations and 19 variables. Subjects in this data set
are each individual movies and there are 808 subjects. A single subject
has all the information related to one movie like budget, language,
title etc.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  Which of the following types of variables are present in your data
  set? (i) nominal; (ii) ordinal; (iii); interval; (iv) ratio. If
  present, name one example of such a variable present in your data set.
  \textbf{[4 points]}
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#No code needed for this Question}
\end{Highlighting}
\end{Shaded}

\textbf{Your Answer:} In this data set we can find all previously
mentioned variables. A nominal variable i.e would be genre, title,
original language without any special order. Furthermore ratio variables
can be found from the data set i.e budget \& revenue. Ordinal variables
like release month and release day. Finally, interval variables like
release year.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  A movie studio wants to know which types of movies are best at
  generating profit. The measure they use for this is the profitability
  ratio, which is defined as \[PR=\frac{Revenue}{Budget}.\] Perform the
  following steps to provide the movie studio with an analysis which
  corresponds to their request:
\end{enumerate}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  Create the variable PR as the revenue of a movie divided by its
  budget. Report its mean, median, maximum, and minimum.
  \textbf{[2 points]}
\item
  As you can probably see from your answer in a.), some movies have a PR
  of ``Inf''. What does this mean? Why are some movies assigned this
  value? \textbf{[2 points]}
\item
  As you can probably see from your answer in a.), some movies have a PR
  of ``NA''. What does this mean? Why are some movies assigned this
  value? \textbf{[2 points]}
\item
  For the movies that have a PR of ``Inf'', set its PR to ``NA''. After
  doing this, report the mean, median, maximum, and minimum of PR. How
  do you interpret the mean? \textbf{[2 points]}
\item
  What does a PR of at least one mean? What is the fraction of movies
  that have a PR of at least one? \textbf{[2 points]}
\item
  Create a boxplot of the variable PR. Make sure it has an appropriate
  title, and appropriate titles and labels for the x- and y-axis.
  Describe the shape of the boxplot. Give \(Q_1\), \(Q_2\), \(Q_3\) and
  \(Q_4\). What does this tell you about the nature of making money in
  the movies industry? \textbf{[2 points]}
\end{enumerate}

For each step, you should provide first all the code you used to answer
the question and then formulate an answer using full sentences.

\emph{Step a}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Movies\_4 }\OtherTok{\textless{}{-}}\NormalTok{ Movies\_4 }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{PR =} \FunctionTok{ifelse}\NormalTok{(budget }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{, revenue }\SpecialCharTok{/}\NormalTok{ budget, }\ConstantTok{NaN}\NormalTok{))}

\NormalTok{Movies\_4 }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}
    \AttributeTok{Mean\_PR =} \FunctionTok{mean}\NormalTok{(PR, }\AttributeTok{na.rm =}\NormalTok{ T),}
    \AttributeTok{Median\_PR =} \FunctionTok{median}\NormalTok{(PR, }\AttributeTok{na.rm =}\NormalTok{ T),}
    \AttributeTok{Max\_PR =} \FunctionTok{max}\NormalTok{(PR, }\AttributeTok{na.rm =}\NormalTok{ T),}
    \AttributeTok{Min\_PR =} \FunctionTok{min}\NormalTok{(PR, }\AttributeTok{na.rm =}\NormalTok{ T))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 1 x 4
##   Mean_PR Median_PR Max_PR Min_PR
##     <dbl>     <dbl>  <dbl>  <dbl>
## 1    2.86      1.54   73.7      0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#question a without the inf. correction:}
\CommentTok{\#Movies\_4 \textless{}{-} Movies\_4 \%\textgreater{}\%}
\CommentTok{\#  mutate(PR = revenue / budget)}
\CommentTok{\#Movies\_4 \%\textgreater{}\%}
\CommentTok{\#  summarise(}
\CommentTok{\#    Mean\_PR = mean(PR, na.rm = T),}
\CommentTok{\#    Median\_PR = median(PR, na.rm = T),}
\CommentTok{\#    Max\_PR = max(PR, na.rm = T),}
\CommentTok{\#    Min\_PR = min(PR, na.rm = T))}
\end{Highlighting}
\end{Shaded}

\textbf{Your Answer:} Mean = 2.864599 Median = 1.535826 Max = 73.67146
Minimum = 0

\textbf{without Inf. removal:} Mean = Inf Median = 1.70 Max = Inf
Minimum = 0

\emph{Step b}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#No code needed for this Question}
\end{Highlighting}
\end{Shaded}

\textbf{Your Answer:}

Some answers have an outcome of ``inf'' because of a divide by zero
error. Some movies have a budget of 0 which causes the PR ratio to be
infinite. We encountered this problem already in answer A, and our
solution to combat this problem was to write an ``ifelse'' function that
will only formulate an answer when the budget is greater than 0.
Otherwise it returns NaN. We than said to remove the NA values

\emph{Step c}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#No code needed for this question}
\end{Highlighting}
\end{Shaded}

\textbf{Your Answer:}

There are multiple possible reasons for there to return NA. The first is
as discussed in b, we assigned that value to observations with a budget
of 0. But if we look at the code without the ``ifelse'' function we see
that PR give a NaN value when both revenue and budget are 0

\emph{Step d}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Movies\_4 }\OtherTok{\textless{}{-}}\NormalTok{ Movies\_4 }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{PR =} \FunctionTok{ifelse}\NormalTok{(budget }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{, revenue }\SpecialCharTok{/}\NormalTok{ budget, }\ConstantTok{NaN}\NormalTok{))}

\NormalTok{Movies\_4 }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}
    \AttributeTok{Mean\_PR =} \FunctionTok{mean}\NormalTok{(PR, }\AttributeTok{na.rm =}\NormalTok{ T),}
    \AttributeTok{Median\_PR =} \FunctionTok{median}\NormalTok{(PR, }\AttributeTok{na.rm =}\NormalTok{ T),}
    \AttributeTok{Max\_PR =} \FunctionTok{max}\NormalTok{(PR, }\AttributeTok{na.rm =}\NormalTok{ T),}
    \AttributeTok{Min\_PR =} \FunctionTok{min}\NormalTok{(PR, }\AttributeTok{na.rm =}\NormalTok{ T))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 1 x 4
##   Mean_PR Median_PR Max_PR Min_PR
##     <dbl>     <dbl>  <dbl>  <dbl>
## 1    2.86      1.54   73.7      0
\end{verbatim}

\textbf{Your Answer:} The mean is equal to 2.864599 The median is equal
to 1.535826 The maximum is equal to 73.67146 The minimum is equal to 0

The way to interpret this mean is by being aware of the difference in
assigned\\
weight. The way we did it was by taking the average of all movies where
each has the same weight. If we took scale into consideration with the
function: \textbf{PriBud\_tot =
sum(Movies\_4}\(revenue, na.rm = T) / sum(Movies_4\)budget, na.rm = T)
Than the mean would be lower ``(2.772)'' because movies with a larger
budget have a lower PR ratio.

\emph{Step e}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Movies\_4 }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}
  \AttributeTok{Frac1 =} \FunctionTok{sum}\NormalTok{(Movies\_4}\SpecialCharTok{$}\NormalTok{PR }\SpecialCharTok{\textgreater{}=} \DecValTok{1}\NormalTok{, }\AttributeTok{na.rm =}\NormalTok{ T) }\SpecialCharTok{/} \FunctionTok{nrow}\NormalTok{(Movies\_4))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 1 x 1
##   Frac1
##   <dbl>
## 1 0.457
\end{verbatim}

\textbf{Your Answer:}

A PR ratio of at least 1 means that the movie broke even, or made a
profit. A fraction of 0.4566832 movies have a PR of 1 or higher

\emph{Step f}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(Movies\_4, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \StringTok{" "}\NormalTok{, }\AttributeTok{y =}\NormalTok{ PR)) }\SpecialCharTok{+}
  \FunctionTok{geom\_boxplot}\NormalTok{(}\AttributeTok{width =} \FloatTok{0.5}\NormalTok{) }\SpecialCharTok{+} 
  \FunctionTok{scale\_y\_continuous}\NormalTok{(}\AttributeTok{n.breaks =} \DecValTok{15}\NormalTok{, }\AttributeTok{limits =} \FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{15}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{x =} \StringTok{"movies"}\NormalTok{,  }
    \AttributeTok{y =} \StringTok{"Profitability Ratio"}\NormalTok{,}
    \AttributeTok{title =} \StringTok{"Boxplot of Profitability Ratios Movies"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: Removed 213 rows containing non-finite outside the scale range
## (`stat_boxplot()`).
\end{verbatim}

\pandocbounded{\includegraphics[keepaspectratio]{Assignment12_files/figure-latex/unnamed-chunk-8-1.pdf}}

\textbf{Your Answer:} The shape of the boxplot is very flat. We
intentionally made our boxplot larger by excluding extreme outliers that
skewed our visual to the point of becoming unreadable. Therefore our
limits for the Y axis are set from 0 (lowest value) to 15. This excludes
14 observations but our box plot becomes much clearer. The values of the
quantiles: Q1 ≈ 0.4, Q2 ≈ 1.5, Q3 ≈ 3.4, Q4 ≈ 14 (or without removed
values Q4 ≈ 73.6) This tells us that the movie business is often
profitable and has massive potential to create extremely high returns

\section{Week 2}\label{week-2}

1 Is your dataset movies4.tsv the full population, or is it a sample of
a larger population? If the latter, how would you describe the full
population? \textbf{[4 points]}

\textbf{Your Answer} The data set Movies\_4 is not the full population
but rather a sample. It contains 808 movies which is fewer than the
total number of movies ever released. As a result, the whole population
would include all movies which fit the dataset's intended period, such
as all films released worldwide (or all films in the original source
database) throughout the relevant years.

2 Let M be the event that a movie director is male. Let R be the runtime
of the movie.

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  Using your data, calculate \(P(M)\). What is \(P(M')\)?. Calculate
  \(P(M')\) as well. \textbf{[1 point]}
\item
  Assume R is normally distributed with \(\mu=107\) and \(\sigma=22\),
  calculate \(P(90 \leq R \leq 120)\). \textbf{[1 point]}
\item
  Calculate \(P(90 \leq R \leq 120)\) empirically using your data. How
  accurate were the assumptions about the distribution of R in 2b? Which
  of the assumptions do you consider the most suspect? Explain.
  \textbf{[2 points]}
\item
  Using your data, calculate \(P(120 \leq R | M')\) \textbf{[2 points]}
\end{enumerate}

\emph{step a}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Prob\_M }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(Movies\_4}\SpecialCharTok{$}\NormalTok{director\_gender }\SpecialCharTok{==} \StringTok{"male"}\NormalTok{, }\AttributeTok{na.rm =}\NormalTok{ T)}
\NormalTok{Prob\_F }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(Movies\_4}\SpecialCharTok{$}\NormalTok{director\_gender }\SpecialCharTok{!=} \StringTok{"male"}\NormalTok{, }\AttributeTok{na.rm =}\NormalTok{ T)}
\end{Highlighting}
\end{Shaded}

\textbf{Your Answer:} P(M)=0.895=89.5\% P(M')=0.105=10.5\%

\emph{step b}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{pnorm}\NormalTok{(}\DecValTok{120}\NormalTok{, }\DecValTok{107}\NormalTok{, }\DecValTok{22}\NormalTok{) }\SpecialCharTok{{-}} \FunctionTok{pnorm}\NormalTok{(}\DecValTok{90}\NormalTok{, }\DecValTok{107}\NormalTok{, }\DecValTok{22}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.5028674
\end{verbatim}

\textbf{Your Answer:} P(90 ≤ R ≤ 120) = 0.503

\emph{step c}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Probability question 2B = 0.5028674}
\NormalTok{Movies\_4 }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}
    \AttributeTok{Prob\_R =} \FunctionTok{mean}\NormalTok{(runtime }\SpecialCharTok{\textgreater{}=} \DecValTok{90} \SpecialCharTok{\&}\NormalTok{ runtime }\SpecialCharTok{\textless{}=} \DecValTok{120}\NormalTok{ , }\AttributeTok{na.rm =}\NormalTok{ T),}
    \AttributeTok{Mean\_run =} \FunctionTok{mean}\NormalTok{(runtime, }\AttributeTok{na.rm =}\NormalTok{ T),}
    \AttributeTok{SD\_RUN =} \FunctionTok{sqrt}\NormalTok{(}\FunctionTok{var}\NormalTok{(runtime, }\AttributeTok{na.rm =}\NormalTok{ T)))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 1 x 3
##   Prob_R Mean_run SD_RUN
##    <dbl>    <dbl>  <dbl>
## 1  0.657     105.   20.6
\end{verbatim}

\textbf{Your Answer:} Our mean is 105.3 which is very close to the
assumed mean of 107. The standard deviation came out as 20.6 which is
decently close to the assumed 22, so the standard deviation would be the
most suspect out of the two.

\emph{step d}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Filter for female movies}
\NormalTok{F\_Movies\_4 }\OtherTok{\textless{}{-}}\NormalTok{ Movies\_4 }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(director\_gender }\SpecialCharTok{!=} \StringTok{"male"}\NormalTok{)}

\CommentTok{\#Proportion R \textgreater{}= 120}
\NormalTok{F\_Movies\_4 }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}
    \AttributeTok{F\_P\_R =} \FunctionTok{mean}\NormalTok{(runtime }\SpecialCharTok{\textgreater{}=} \DecValTok{120}\NormalTok{, }\AttributeTok{na.rm =}\NormalTok{ T))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 1 x 1
##   F_P_R
##   <dbl>
## 1 0.188
\end{verbatim}

\textbf{Your Answer:} P(120 ≤ R\textbar M ′) = 0.1875=19\%

3 For this question, you will again use the profitability ratio PR. Make
sure that PR is defined the same way as in question 3d of week 1. For
this question, you will assume that your data set is the full
population.

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  What is the mean of the variable PR in your data set?
  \textbf{[2 points]}
\item
  Create a new data set, called movies\_sample. Make sure that it is a
  random sample of your data set of 25 movies. What is the mean of PR in
  this random sample? How does it compare to the mean of PR in 3a?
  \textbf{[2 points]}
\item
  In a for loop, create 100 different samples of 25 movies, as in b, and
  estimate the mean within each sample. Save the mean of each sample in
  a vector called sample\_means. So the first position of the vector
  would have the mean of the first sample, the second position the mean
  of the second sample, etc. Print this vector. \textbf{[2 points]}
\item
  Summarize and make a histogram of sample\_means. What is the mean,
  standard deviation and shape of its distribution? \textbf{[2 points]}
\item
  Using the formulas of the \emph{Central Limit Theorem}, give the
  distribution of the sample mean of PR in a sample of 25 movies from
  you population (including its expected value and standard deviation).
  How do these values compare to your answers at d.)?
  \textbf{[2 points]}
\end{enumerate}

\emph{step a}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Movies\_4 }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{summarise}\NormalTok{(}\AttributeTok{Mean\_PR =} \FunctionTok{mean}\NormalTok{(PR, }\AttributeTok{na.rm =}\NormalTok{ T))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 1 x 1
##   Mean_PR
##     <dbl>
## 1    2.86
\end{verbatim}

\textbf{Your Answer:} Mean(PR) = 2.864599

\emph{step b}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Movies\_sample }\OtherTok{=}\NormalTok{ Movies\_4[}\FunctionTok{sample}\NormalTok{(}\FunctionTok{nrow}\NormalTok{(Movies\_4),}\DecValTok{25}\NormalTok{, }\AttributeTok{replace =}\NormalTok{ F),]}

\NormalTok{Movies\_sample }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{summarise}\NormalTok{(}\AttributeTok{Mean\_S\_PR =} \FunctionTok{mean}\NormalTok{(PR, }\AttributeTok{na.rm =}\NormalTok{ T))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 1 x 1
##   Mean_S_PR
##       <dbl>
## 1      1.94
\end{verbatim}

\textbf{Your Answer:} Mean(PR) = 3.458819 whilst the mean from the
original data set was 2.86 so compared to the mean in 3a this sample has
a significantly higher (mean) PR than the original data set.

\emph{step c}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{837}\NormalTok{)}
\NormalTok{sample\_means }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{()}

\ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\SpecialCharTok{:}\DecValTok{100}\NormalTok{)) }
\NormalTok{  \{Movies\_sample2 }\OtherTok{=}\NormalTok{ Movies\_4[}\FunctionTok{sample}\NormalTok{(}\FunctionTok{nrow}\NormalTok{(Movies\_4),}\DecValTok{25}\NormalTok{, }\AttributeTok{replace =}\NormalTok{ F),];       sample\_means[i] }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(Movies\_sample2}\SpecialCharTok{$}\NormalTok{PR, }\AttributeTok{na.rm =}\NormalTok{ T)\}}
\end{Highlighting}
\end{Shaded}

\textbf{Your Answer:} This function will create, just like in question b
a data set (movies\_sample2) that will have 25 samples of the original
Movies\_4 data set. We than asked, just like in question b to calculate
the mean of the PR. This was written in our for loop which repeated this
tasked 100 times and we printed the results in the vector
``sample\_means''.It seems like from our sample that most sample means
lie in between the values of 1.5 and 3.5

\emph{step d}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{DF\_sample\_means }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(sample\_means)}

\NormalTok{DF\_sample\_means }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}
    \AttributeTok{Mean\_sam =} \FunctionTok{mean}\NormalTok{(sample\_means, }\AttributeTok{na.rm =}\NormalTok{ T),}
    \AttributeTok{SD\_sam =} \FunctionTok{sqrt}\NormalTok{(}\FunctionTok{var}\NormalTok{(sample\_means, }\AttributeTok{na.rm =}\NormalTok{ T)))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Mean_sam   SD_sam
## 1 2.889988 1.145964
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(DF\_sample\_means, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ sample\_means)) }\SpecialCharTok{+}
  \FunctionTok{geom\_histogram}\NormalTok{(}\AttributeTok{bins =} \DecValTok{8}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Assignment12_files/figure-latex/unnamed-chunk-16-1.pdf}}
\textbf{Your Answer:} Our PR mean of our sample mean is 2.89. Which is
very close to the mean PR of our original data set of 2.864. And our SD
is 1.146. Our histogram is skewed right with outliers.

\emph{step e} \textbf{Your Answer:} the original population mean is
2.864 and the standard deviation is 5.43 {[}Movies\_4 \%\textgreater\%
summarise( Mean\_PR = mean(PR, na.rm = T), SD\_RUN = sqrt(var(PR, na.rm
= T))){]} the expected value of the sample mean is equal to the mean of
the population so E(mean) = 2.864 which is very similar to our answer of
2.89 in question d

the standard deviation of the mean will be the standard deviation of the
original population divided by sqrt(n) (sample size) = sqrt(25) 5.43 / 5
= 1.086 this is also close to our answer of 1.146 in question d

\section{Week 3}\label{week-3}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  For the next part of the assignment, assume that the movies in your
  data frame are a random sample of a larger population of movies.
\end{enumerate}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\item
  Create a new data set that only includes movies that are of the genre
  ``Thriller''. For these thriller movies, give a 99 percent confidence
  interval for the variable \emph{vote\_average}. \textbf{[2 points]}
\item
  According to IMDB, the average movie is rated with a 6.5. Using your
  data, test for the null hypothesis that thriller movies are at least
  as good as the average movie, against the alternative hypothesis that
  thriller movies are rated worse than the average movie. Test this
  hypothesis using an approporiate five-step procedure. What is your
  p-value and what do you conclude? \textbf{[2 points]}
\end{enumerate}

\emph{step a}

\textbf{Your Answer:}

Write your formulated response here.

\emph{step b}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\end{Highlighting}
\end{Shaded}

\textbf{Your Answer:}

Write your formulated response here.

2

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  How many movies in your sample had a female lead actor? How many had a
  male lead actor? \textbf{[2 points]}
\item
  Test the null hypothesis that for any given movie the chance that the
  lead actor is male or female is equal. Clearly state your null
  hypothesis and alternative hypothesis, and your chosen significance
  level. Use an appropriate R function to test your hypothesis, and
  state your conclusion. Also give the p-value that corresponds to your
  test statistic. \textbf{[2 points]}
\item
  What is the variance of the profitability ratio (PR) for movies with a
  male lead actor? What is the variance of profitability ratio for
  movies with a female lead actor? Make sure that PR is defined in the
  same way as in week 1. \textbf{[2 points]}
\item
  Assume that the variance of PR for movies with a male lead actor in
  your data is the same as the variance for movies with a male lead
  actor in your population (that is, there is no sampling uncertainty in
  this estimate). Now, set up a hypothesis test to test for the null
  hypothesis that the PR for movies with a female lead is equal to the
  variance for movies with a male lead actor. Clearly state your null
  hypothesis and alternative hypothesis, and your chosen significance
  level. Calculate your test statistic and tell how your test statistic
  is distributed, and state your conclusion. Also give the p-value that
  corresponds to your test statistic. \textbf{[2 points]}
\end{enumerate}

\emph{step a}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\end{Highlighting}
\end{Shaded}

\textbf{Your Answer:}

Write your formulated response here.

\emph{step b}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\end{Highlighting}
\end{Shaded}

\textbf{Your Answer:}

Write your formulated response here.

\emph{step c}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\end{Highlighting}
\end{Shaded}

\textbf{Your Answer:}

Write your formulated response here.

\emph{step d}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\end{Highlighting}
\end{Shaded}

\textbf{Your Answer:}

Write your formulated response here.

3

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  Create a new variable called genre2. Make sure that the three most
  popular genres remain the same, but that all the other genres get
  categorized into one genre called ``Other''. Report a frequency table
  of this new variable genre2. \textbf{[2 points]}
\item
  Create a scatter plot with each type of genre2 on the x axis and the
  mean of PR within that genre on the y-axis. Make sure it has an
  appropriate title, and appropriate titles and labels for the x- and
  y-axis. Which movie genre has the highest PR? Which has the lowest?
  \textbf{[2 points]}
\item
  Recreate the scatter plot, but now add bars around each point,
  indicating the 95\% confidence interval. \textbf{[2 points]}
\item
  Now, create a new data frame which is a random subsample of n=100 of
  your full data frame. Recreate the plot in c.) How do the confidence
  intervals compare to the confidence intervals you plotted in c.)?
  \textbf{[2 points]}
\end{enumerate}

\emph{step a}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\end{Highlighting}
\end{Shaded}

\textbf{Your Answer:}

Write your formulated response here.

\emph{step b}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\end{Highlighting}
\end{Shaded}

\textbf{Your Answer:}

Write your formulated response here.

\emph{step c}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\end{Highlighting}
\end{Shaded}

\textbf{Your Answer:}

Write your formulated response here.

\emph{step d}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\end{Highlighting}
\end{Shaded}

\textbf{Your Answer:}

Write your formulated response here.

\section{Week 4}\label{week-4}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  There is an argument going on in the movie studio. \emph{Bob} claims
  that production budgets are getting out of hand, and that the studio
  should focus on making cheaper movies. \emph{Chantal} disagrees. She
  tells Bob that ``The profitability ratio of the movie will remain
  similar, no matter how much the budget is'\,'.
\end{enumerate}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  Set up a regression model to test Chantal's claim, and estimate it.
  That is, estimate:
  \[\text{PR}_i=\beta_0+\beta_1 \text{Budget}_i +\varepsilon_i.\] Print
  a summary of your estimated model. \textbf{[2 points]}
\item
  What is the estimated value of \(\beta_1\) how do you interpet it?
  \textbf{[2 points]}
\item
  Test for the null hypothesis that \(\beta_1 = 0\). Report the p-value
  and state your conclusion. \textbf{[2 points]}
\item
  Who do you think is correct? Bob or Chantal? What would you advise the
  movie studio to do? \textbf{[2 points]}
\item
  Make a histogram of the residuals of your model. Based on the
  histogram, do you have any reason to doubt the validity of your model?
  Explain. \textbf{[2 points]}
\item
  Estimate hatvalues for each observation that you used to estimate your
  model. Do any hatvalues exceed the critical value? Based on this
  analysis, do you hvae any reason to doubt the validity of your model?
  \textbf{[2 points]}
\item
  Based on your analysis in f.), estimate your model again, but remove
  any outliers. Print a summary of your model and again test for the
  null hypothesis that \(\beta_1 = 0\). What do you conclude? Based on
  this new model, would your advice to the movie studio in question d.
  change? \textbf{[2 points]}
\end{enumerate}

\emph{step a}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\end{Highlighting}
\end{Shaded}

\textbf{Your Answer:}

Write your formulated response here.

\emph{step b}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\end{Highlighting}
\end{Shaded}

\textbf{Your Answer:}

Write your formulated response here.

\emph{step c}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\end{Highlighting}
\end{Shaded}

\textbf{Your Answer:}

Write your formulated response here.

\emph{step d}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\end{Highlighting}
\end{Shaded}

\textbf{Your Answer:}

Write your formulated response here.

\emph{step e}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\end{Highlighting}
\end{Shaded}

\textbf{Your Answer:}

Write your formulated response here.

\emph{step f}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\end{Highlighting}
\end{Shaded}

\textbf{Your Answer:}

Write your formulated response here.

\emph{step g}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\end{Highlighting}
\end{Shaded}

\textbf{Your Answer:}

Write your formulated response here.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
\end{enumerate}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  Make a scatterplot with vote\_average on the y-axis, and runtime on
  the x-axis. Within the same scatterplot, draw a straight line which
  summarizes the association between the average vote and the runtime.
  \textbf{[3 points]}
\item
  Using the insights from the scatterplot, your linear model, and your
  data, find an example of a movie that vastly overperformed. That
  means, find a movie that had much higher average vote than expected,
  given its runtime. For this movie, report its vote\_average, its
  predicted vote\_average, and its residual. \textbf{[3 points]}
\end{enumerate}

\emph{step a}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\end{Highlighting}
\end{Shaded}

\textbf{Your Answer:}

Write your formulated response here.

\emph{step b}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\end{Highlighting}
\end{Shaded}

\textbf{Your Answer:}

Write your formulated response here.

\section{Week 5}\label{week-5}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  Create a plot of the mean PR by year of release. Include 95\%
  confidence intervals around each mean Do you see any indication of a
  time trend in the PR? \textbf{[4 points]}
\item
  Estimate an OLS model which has as dependent variable the PR of a
  movie, and as independent variable the log of budget, a dummy for each
  level that genre2 can take, and the year of release. Show a summary of
  the resulting model and interpret each coefficient.
  \textbf{[4 points]}
\end{enumerate}

The movie studio that you work is releasing a new movie in May of 2026.
It will be a Comedy movie with a budget of 40,000,0000. It will have a
runtime of 160 minutes.

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  Estimate a model that is able to predict the revenue of this movie.
  Give its predicted revenue and include a 95\% prediction interval.
  \textbf{[6 points]}
\item
  Plot the residuals against various independent variables in the model.
  Do you find any evidence of heteroskedasticity? \textbf{[2 points]}
\item
  The movie is set in Germany. The director wants to make the movie with
  only german-speaking actors. The executive producer is strongly
  against this, as she is afraid that movies that are not english spoken
  will have a low profit ratio. Estimate a model that can test whether
  the language spoken impacts the PR of this specific movie. Use an
  appropriate hypothesis test to test whether the language. What would
  you advise the movie studio regarding the language to be spoken?
  \textbf{[6 points]}
\end{enumerate}

\emph{step a}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\end{Highlighting}
\end{Shaded}

\textbf{Your Answer:}

Write your formulated response here.

\emph{step b}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\end{Highlighting}
\end{Shaded}

\textbf{Your Answer:}

Write your formulated response here.

\emph{step c}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\end{Highlighting}
\end{Shaded}

\textbf{Your Answer:}

Write your formulated response here.

\emph{step d}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\end{Highlighting}
\end{Shaded}

\textbf{Your Answer:}

Write your formulated response here.

\emph{step e}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#WRITE YOUR CODE HERE}
\end{Highlighting}
\end{Shaded}


\end{document}
